# Routing
routingType:	yml

# Template Engine
template:    twig

# database configuration
database:
    user:		root
    password: sdiallo88	
    dbname:		projectmanager
    host:		localhost
    engine:		mysql

# language (tool development)
language:    fr

# environnement (dev | prod)
environnement:    prod

# Permit to check if a project is already started
existingproject:    true

#Salt MDP
salt: $ù$ded

#Root to forbidden page
redirect_non_authorized: /forbidden
