
default_show:
	pattern:	 / 
	controller: home:index
home_show:
	pattern:	/home
	controller: home:show 
account_show:
	pattern:	/account
	controller: account:show 
ticket_show:
	pattern:	/ticket
	controller: ticket:show 
dashboard_show:
	pattern:	/dashboard
	controller: dashboard:show 
roadmap_show:
	pattern:	/roadmap
	controller: roadmap:show 
activity_show:
	pattern:	/activity
	controller: activity:show 
announcement_show:
	pattern:	/announcement
	controller: announcement:show
account_connect:
	pattern:	/connect
	controller: account:connect
account_signup:
	pattern:	/signup
	controller: account:signup
account_deconnect:
	pattern:	/deconnect
	controller: account:deconnect
