
default_index:
	pattern:	 / 
	controller: home:index
home_index:
	pattern:	/home
	controller: home:index
home_newProject:
    pattern:    /new-project
    controller: home:newProject

# Account Controller

account_index:
	pattern:	/account
	controller: account:index
	requirements:
            only_connected: true

account_connect:
	pattern:	/connect
	controller: account:connect

account_signup:
	pattern:	/signup
	controller: account:signup

account_deconnect:
	pattern:	/deconnect
	controller: account:deconnect

account_forbidden:
    pattern:    /forbidden
    controller: account:forbidden

account_member:
	pattern:	/{project}/member/{member}/
	controller: account:memberDetail
    requirements:
        project:   string
        member:   string
        only_connected: true

# Tickets Controller

ticket_index:
    pattern:    /{project}/tickets/
    controller: ticket:index
    requirements:
        project:   string
        only_connected: true

ticket_detail:
	pattern:	/{project}/ticket/{ticket}/
	controller: ticket:detail
	    project:   string
	    ticket:   string
        only_connected: true

dashboard_index:
    pattern:    /{project}/
    controller: dashboard:index
    requirements:
        project:   string
        only_connected: true

# Activity Controller

activity_index:
    pattern:    /{project}/activity
    controller: activity:index
    requirements:
        project:   string
        only_connected: true

announce_detail:
    pattern:    /{project}/announce/{announce}/
    controller: activity:detail
    requirements:
        project:   string
        announce:   string
        only_connected: true

# Roadmap Controller

roadmap_index:
    pattern:    /{project}/roadmaps
    controller: roadmap:index
    requirements:
        project:   string
        only_connected: true

roadmap_detail:
    pattern:    /{project}/roadmap/{roadmap}/
    controller: roadmap:detail
    requirements:
        project:   string
        roadmap:   string
        only_connected: true

