
default_index:
	pattern:	 / 
	controller: home:index
home_index:
	pattern:	/home
	controller: home:index

# Account Controller

account_index:
	pattern:	/my-account
	controller: account:index
	requirements:
            only_connected: true

account_connect:
	pattern:	/connect
	controller: account:connect

account_signup:
	pattern:	/signup
	controller: account:signup

account_deconnect:
	pattern:	/deconnect
	controller: account:deconnect

account_forbidden:
    pattern:    /forbidden
    controller: account:forbidden


organization_changeMemberInfos:
    pattern:    /change-member-informations
    controller: organization:changeMemberInfos
    requirements:
        only_connected: true
        ajax: true
        exclude_groups : visitor|user



# Tickets Controller

ticket_index:
    pattern:    /{project}/tickets/
    controller: ticket:index
    requirements:
        project:   string
        only_connected: true

ticket_detail:
	pattern:	/{project}/ticket/{ticket}/
	controller: ticket:detail
	    project:   string
	    ticket:   string
        only_connected: true
        exclude_groups : visitor

# Dashboard Controller

dashboard_index:
    pattern:    /{project}/
    controller: dashboard:index
    requirements:
        project:   string
        only_connected: true

# Activity Controller

activity_index:
    pattern:    /{project}/activity
    controller: activity:index
    requirements:
        project:   string
        only_connected: true

announce_detail:
    pattern:    /{project}/announce/{announce}/
    controller: activity:detail
    requirements:
        project:   string
        announce:   string
        only_connected: true
        exclude_groups : visitor

activity_newProject:
    pattern:    /new-project/{name}/{desc}
    controller: activity:newProject
    requirements:
        project:   string
        name: string
        desc: string
        id: int
        only_connected: true
        ajax: true

activity_newAnnounce:
    pattern:    /{project}/new-announce/{name}/{desc}/{id}
    controller: activity:newAnnounce
    requirements:
        project:   string
        only_connected: true
        ajax: true
        exclude_groups : visitor|user

activity_newService:
    pattern:    /{project}/new-service/{name}/{id}
    controller: activity:newService
    requirements:
        project:   string
        only_connected: true
        ajax: true
        exclude_groups : visitor|user

activity_newMember:
    pattern:    /{project}/new-member/{login1}/{login2}/{login3}/{login4}/{login5}/{id}
    controller: activity:newMember
    requirements:
        project:   string
        only_connected: true
        ajax: true
        exclude_groups : visitor|user

activity_newTicket:
    pattern:    /{project}/new-ticket
    controller: activity:newTicket
    requirements:
        only_connected: true
        ajax: true
        exclude_groups : visitor|user

# Organization Controller

organization_index:
    pattern:    /{project}/organization
    controller: organization:index
    requirements:
        project:   string
        only_connected: true

organization_detail:
    pattern:    /{project}/roadmap/{roadmap}/
    controller: organization:detail
    requirements:
        project:   string
        roadmap:   string
        only_connected: true
        exclude_groups : visitor

organization_newRoadmap:
    pattern:    /{project}/new-roadmap/{name}/{desc}/{id}
    controller: organization:newRoadmap
    requirements:
        project:   string
        only_connected: true
        ajax: true
        exclude_groups : visitor|user

