
default_show:
	pattern:	 / 
	controller: home:index
home_show:
	pattern:	/home
	controller: home:index


# Tickets Controller

ticket_index:
    pattern:    /project/{id_project}/tickets
    controller: ticket:index
    requirements:
        id_project:   int

ticket_detail:
	pattern:	/project/{id_project}/ticket/{name_ticket}/{id_ticket}
	controller: ticket:detail

dashboard_index:
    pattern:    /project/{id_project}
    controller: dashboard:index
    requirements:
        id_project:   int

# Activity Controller

activity_index:
    pattern:    /project/{id_project}/activity
    controller: activity:index
    requirements:
        id_project:   int

announce_detail:
    pattern:    /project/{id_project}/announce/{name_announce}/{id_announce}
    controller: activity:detail
    requirements:
        id_project:   int


# Roadmap Controller

roadmap_index:
    pattern:    /project/{id_project}/roadmaps
    controller: roadmap:index
    requirements:
        id_project:   int

roadmap_detail:
    pattern:    /project/{id_project}/roadmap/{name_roadmap}/{id_roadmap}
    controller: roadmap:detail
    requirements:
        id_project:   int


# Account Controller

account_index:
	pattern:	/account
	controller: account:index

account_connect:
	pattern:	/connect
	controller: account:connect

account_signup:
	pattern:	/signup
	controller: account:signup

account_deconnect:
	pattern:	/deconnect
	controller: account:deconnect

account_member:
	pattern:	/project/{id_project}/member/{name_member}/{id_member}
	controller: account:memberDetail
